# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #time, velocity, angular vel
<<<<<<< HEAD
  - [0.7, 0.43, 0]
  - [2.3, 0.43, 3.2]
  - [0.3, 0.43, 0.0]
turn_right:
  - [0.6, 0.43, 0]
  - [1.5, 0.3, -4.506]
  - [0.1, 0.43, 0.0]
turn_forward:
  - [2.8, 0.43, 0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
turn_back:
  - [1, 0.4, 0.0]
  - [1.7, 0.4, 7.5]
  - [0.3, 0.3,0]
=======
  - [0.9, 0.43, 0]
#  - [2.2, 0.43, 2.896]
  - [2.3, 0.43, 3.2]
#  - [2, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
turn_right:
  - [0.6, 0.43, 0]
  - [1.5, 0.3, -4.506]
#  - [0.1, 0.0, 0.0]
  - [1.0, 0.43, 0.0]
turn_forward:
  - [2.5, 0.43, 0.4]
  - [0.5, 0.43, 0.0]
  - [0.0, 0.0, 0.0]
turn_back:
  - [ 1.2, 0.4, 0.0]
  - [1.2,0.3,6.5]
  - [0.8,0.4,0]
>>>>>>> 2d356ff5df7440b437fd8915a698c3f4ba9b0c0c
# turn_stop:
#   - [0.2, 0.0, 0.0]

#do we want to update the values based on where/what angle we stop at.
trajectory_reparam: 0
