img_size: [120,160]
top_cutoff: 40

# should be an array of 2 elements. The first is the name of the class
# and the second should be the parameters. 
# The class should be an abstract instance of LineDetectorInterface
detector: 
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [80,200]
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1
     
      hsv_white1:  [0,0,220]  # blue1 is [100,50,150]
      hsv_white2:  [180,15,255]  # blue2 is [150,255,255]
<<<<<<< HEAD
      hsv_yellow1: [90,100,100] #original yellow1 [25,30,70]
      hsv_yellow2: [130,255,255] #45 255 255
=======
      hsv_yellow1: [25,30,70] #original yellow1 [25,140,100]
      hsv_yellow2: [45,255,255]
>>>>>>> 2d356ff5df7440b437fd8915a698c3f4ba9b0c0c
      hsv_red1:    [0,70,80]
      hsv_red2:    [10,255,255]
      hsv_red3:    [170,70,80]
      hsv_red4:    [180,255,255]
<<<<<<< HEAD
      hsv_blue1:   [90,100,100]
      hsv_blue2:   [130,255,255]
=======
>>>>>>> 2d356ff5df7440b437fd8915a698c3f4ba9b0c0c
